export const ACTIONS = {
  LOAD_OLD_TODOS: 'loadOldTodos',
  RENDER_TODOS: 'renderTodos',
  NEW_TODO: 'newTodo',
  REMOVE_TODO: 'removeTodo',
  CHECK_TODO: 'checkTodo',
  CLICK_ON_TODO: 'clickOnTodo',
  CLEAR_COMPLETED_TODOS: 'clearComplitedTodos',
  SHOW_ACTIVE_TODOS: 'showActiveTodos',
  SHOW_COMPLETED_TODOS: 'showComplitedTodos',
  SHOW_ALL_TODOS: 'showAllTodos',
  TOGGLE_CHECKED_ALL_TODOS: 'toggleCheckedAllTodos',
  HIDE_TODOS_OPTIONS: 'hideTodosOptions',
  SHOW_TODOS_OPRIONS: 'showTodosOptions',
  UPDATE_TODOS_OPTIONS: 'updateTodosOptions',
  DRAG_AND_DROP: 'dragAndDrop',
  UPDATE_SUBLINE: 'updateSubline',
}
