export const ACTION_TYPES = {
  ADD_NEW_TODO: 'ADD_NEW_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  CHECK_TODO: 'CHECK_TODO',
  CHECK_ALL: 'CHECK_ALL',
  CHANGE_TODO_DESCRIPTION: 'CHANGE_TODO_DESCRIPTION',
  RERENDER_TODOS_LIST: 'RERENDER_TODOS_LIST',
  TOGGLE_CHECK_ALL: 'TOGGLE_CHECK_ALL',
  SHOW_COMPLETED_TODOS: 'SHOW_COMPLETED_TODOS',
  SHOW_ALL_TODOS: 'SHOW_ALL_TODOS',
  SHOW_ACTIVE_TODOS: 'SHOW_ACTIVE_TODOS',
}
